spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://124.221.100.10:4306/happy_plus?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: admin
      password: RwCOvcvFFmc0


mybatis-plus:
  # 定义mybatis映射文件的位置
  mapper-locations: classpath:/mapper/*Mapper.xml

server:
  port: 8033


